from __future__ import annotations

import csv
import json
import logging
import os
import urllib.error
import urllib.parse
import urllib.request
import base64
import re
from datetime import datetime
from pathlib import Path
from typing import Any

from langchain_ollama import ChatOllama

from graphrag_weaviate.config import Settings
from graphrag_weaviate.logging_utils import setup_logging
from graphrag_weaviate.models import ApiJudgeOutput
from graphrag_weaviate.retrieval import RetrievalService
from graphrag_weaviate.storage import WeaviateGraphStore
from graphrag_weaviate.utils import truncate_text

try:
    import psycopg  # type: ignore
except ImportError:  # pragma: no cover
    psycopg = None

try:
    import psycopg2  # type: ignore
except ImportError:  # pragma: no cover
    psycopg2 = None

DOC_ID_OR_MKB_CODE = os.getenv("DOC_ID_OR_MKB_CODE", "25_2")
MANIFEST_PATH = os.getenv("MANIFEST_PATH", "manifest.csv")
ONE_C_APPOINTMENTS_URL = os.getenv(
    "ONE_C_APPOINTMENTS_URL",
    "<ONE_C_APPOINTMENTS_URL>",
)
ONE_C_LOGIN = os.getenv("ONE_C_LOGIN") or os.getenv("ONE_C_USERNAME") or os.getenv("LOGIN") or ""
ONE_C_PASSWORD = os.getenv("ONE_C_PASSWORD") or os.getenv("PASSWORD") or ""
ONE_C_TIMEOUT_SECONDS = float(os.getenv("ONE_C_TIMEOUT_SECONDS", "15"))
POSTGRES_DSN = os.getenv("POSTGRES_DSN", "")
POSTGRES_DB = os.getenv("POSTGRES_DB", "")
LOG_FILE = "logs/docsToGraphRAG.log"
CONTEXT_TARGET = int(os.getenv("CONTEXT_TARGET", "10"))
SCORES_SYSTEM_PROMPT = os.getenv(
    "SCORES_SYSTEM_PROMPT",
    (
        "Ты ассистент внутреннего контроля качества заполнения медицинского приёма в российской клинике. "
        "Используй только предоставленные фрагменты клинических рекомендаций и входной JSON визита. "
        "Не используй внешние медицинские знания."
    ),
)


def fetch_appointments_from_1c() -> list[dict[str, Any]]:
    if not ONE_C_APPOINTMENTS_URL:
        raise ValueError("ONE_C_APPOINTMENTS_URL is not set")
    if ONE_C_APPOINTMENTS_URL.startswith("<") and ONE_C_APPOINTMENTS_URL.endswith(">"):
        raise ValueError("Set real ONE_C_APPOINTMENTS_URL in environment")
    if not ONE_C_LOGIN or not ONE_C_PASSWORD:
        raise ValueError("ONE_C_LOGIN and ONE_C_PASSWORD (or LOGIN/PASSWORD) must be set")

    basic_token = base64.b64encode(f"{ONE_C_LOGIN}:{ONE_C_PASSWORD}".encode("utf-8")).decode("ascii")
    current_day = datetime.now().strftime("%d.%m.%Y")
    query_params = urllib.parse.urlencode({"datebegin": current_day, "dateend": current_day})
    separator = "&" if "?" in ONE_C_APPOINTMENTS_URL else "?"
    request_url = f"{ONE_C_APPOINTMENTS_URL}{separator}{query_params}"

    request = urllib.request.Request(
        request_url,
        headers={"Accept": "application/json", "Authorization": f"Basic {basic_token}"},
        method="GET",
    )

    try:
        with urllib.request.urlopen(request, timeout=ONE_C_TIMEOUT_SECONDS) as response:
            payload = json.loads(response.read().decode("utf-8"))
    except urllib.error.URLError as exc:
        raise RuntimeError(f"Failed to fetch appointments from 1C: {exc}") from exc

    if isinstance(payload, list):
        return [item for item in payload if isinstance(item, dict)]
    if isinstance(payload, dict):
        appointments = payload.get("appointments")
        if isinstance(appointments, list):
            return [item for item in appointments if isinstance(item, dict)]
        return [payload]
    raise ValueError("Unsupported 1C response format")


def connect_postgres():
    if not POSTGRES_DSN:
        raise ValueError("POSTGRES_DSN is not set")
    if not POSTGRES_DB:
        raise ValueError("POSTGRES_DB is not set")

    db_from_dsn = extract_db_name_from_dsn(POSTGRES_DSN)
    if db_from_dsn and db_from_dsn != POSTGRES_DB:
        raise ValueError(f"POSTGRES_DB ({POSTGRES_DB}) does not match DB in POSTGRES_DSN ({db_from_dsn})")

    if psycopg is not None:
        return psycopg.connect(POSTGRES_DSN)
    if psycopg2 is not None:
        return psycopg2.connect(POSTGRES_DSN)
    raise RuntimeError("Neither psycopg nor psycopg2 is installed")


def extract_db_name_from_dsn(dsn: str) -> str | None:
    parsed = urllib.parse.urlparse(dsn)
    if parsed.scheme and parsed.path and parsed.path != "/":
        return parsed.path.lstrip("/")
    match = re.search(r"(?:^|\\s)(?:dbname|database)\\s*=\\s*([^\\s]+)", dsn)
    if match:
        return match.group(1).strip().strip("'\"")
    return None


def ensure_medkard_table(conn) -> None:
    create_sql = """
    CREATE TABLE IF NOT EXISTS public."MedKard" (
      id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      created_at timestamp with time zone NOT NULL DEFAULT now(),
      visit_guid_1c text NOT NULL,
      score_visit_identification integer NOT NULL,
      score_anamnes integer NOT NULL,
      score_inspection integer NOT NULL,
      score_dynamic integer NOT NULL,
      score_diagnosis integer NOT NULL,
      score_recommendations integer NOT NULL,
      score_structure integer NOT NULL,
      issues text NULL,
      summary text NULL,
      score_overall integer NOT NULL,
      risk_level text NOT NULL,
      "Inspection_data" jsonb NULL,
      diagnosis_data jsonb NULL,
      services_data jsonb NULL,
      visit_date date NULL,
      human_readable text NULL,
      patient text NULL,
      CONSTRAINT "MedKard_pkey" PRIMARY KEY (id),
      CONSTRAINT "MedKard_visit_guid_1c_key" UNIQUE (visit_guid_1c)
    ) TABLESPACE pg_default;
    """
    with conn.cursor() as cur:
        cur.execute(create_sql)


def normalize_mkb_code(code: str) -> str:
    return code.strip().upper().replace(" ", "")


def split_manifest_mkb(raw: str) -> list[str]:
    out = []
    for token in re.split(r"[,;]", raw or ""):
        cleaned = normalize_mkb_code(token)
        if cleaned:
            out.append(cleaned)
    return out


def load_manifest_mkb_index(path: str) -> tuple[dict[str, str], dict[str, str]]:
    exact: dict[str, str] = {}
    by_group: dict[str, str] = {}
    manifest_path = Path(path)
    if not manifest_path.exists():
        return exact, by_group

    with manifest_path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            doc_id = str(row.get("ID") or row.get("doc_id") or "").strip()
            if not doc_id:
                continue
            mkb_field = str(row.get("МКБ-10") or row.get("MKB-10") or row.get("MKB") or "").strip()
            for code in split_manifest_mkb(mkb_field):
                exact.setdefault(code, doc_id)
                group = code.split(".", 1)[0]
                if group:
                    by_group.setdefault(group, doc_id)
    return exact, by_group


def extract_mkb_codes_from_appointment(appointment: dict[str, Any]) -> list[str]:
    diagnosis = appointment.get("Диагнозы")
    found: list[str] = []
    if isinstance(diagnosis, list):
        for item in diagnosis:
            if not isinstance(item, dict):
                continue
            code = normalize_mkb_code(str(item.get("КодМКБ", "")))
            if code and code not in found:
                found.append(code)
            details = str(item.get("Детализация", ""))
            for matched in re.findall(r"\b[A-ZА-Я]\d{2}(?:\.\d+)?\b", details.upper()):
                mkb = normalize_mkb_code(matched)
                if mkb and mkb not in found:
                    found.append(mkb)
    return found


def resolve_doc_id_from_manifest(
    appointment: dict[str, Any],
    exact_index: dict[str, str],
    group_index: dict[str, str],
) -> tuple[str, list[str], str | None]:
    mkb_codes = extract_mkb_codes_from_appointment(appointment)
    for code in mkb_codes:
        doc_id = exact_index.get(code)
        if doc_id:
            return doc_id, mkb_codes, code
    for code in mkb_codes:
        group = code.split(".", 1)[0]
        doc_id = group_index.get(group)
        if doc_id:
            return doc_id, mkb_codes, code
    return DOC_ID_OR_MKB_CODE, mkb_codes, None


def _to_chunk_dict(chunk: Any) -> dict[str, Any]:
    return {
        "chunk_id": chunk.chunk_id,
        "section_path": chunk.section_path,
        "page_start": chunk.page_start,
        "page_end": chunk.page_end,
        "chunk_type": chunk.chunk_type.value if hasattr(chunk.chunk_type, "value") else str(chunk.chunk_type),
        "chunk_text": chunk.chunk_text,
    }


def build_retrieval_queries(appointment: dict[str, Any], mkb_codes: list[str]) -> list[str]:
    queries: list[str] = []
    diagnosis = appointment.get("Диагнозы")
    if isinstance(diagnosis, list):
        for item in diagnosis:
            if not isinstance(item, dict):
                continue
            code = normalize_mkb_code(str(item.get("КодМКБ", "")))
            detail = str(item.get("Детализация", "")).strip()
            name = str(item.get("НаименованиеМКБ", "")).strip()
            merged = " ".join(part for part in [code, name, detail] if part).strip()
            if merged:
                queries.append(merged)

    inspection = appointment.get("ДанныеОсмотра")
    if isinstance(inspection, list):
        for item in inspection:
            if not isinstance(item, dict):
                continue
            param = str(item.get("Параметр", "")).strip().lower()
            value = str(item.get("Значение", "")).strip()
            if not value:
                continue
            if (
                "рекомендац" in param
                or "план леч" in param
                or "жалоб" in param
                or "динамик" in param
                or "анамн" in param
                or "диагноз" in param
            ):
                queries.append(value[:500])

    if mkb_codes:
        queries.append(" ".join(mkb_codes))

    if not queries:
        queries.append(json.dumps(appointment, ensure_ascii=False)[:1200])

    uniq: list[str] = []
    for q in queries:
        qn = q.strip()
        if qn and qn not in uniq:
            uniq.append(qn)
    return uniq[:7]


def evaluate_scores_with_llm(
    llm: ChatOllama,
    retrieval: RetrievalService,
    doc_id: str,
    appointment: dict[str, Any],
    mkb_codes: list[str],
    log: logging.Logger,
) -> dict[str, Any]:
    retrieval_queries = build_retrieval_queries(appointment=appointment, mkb_codes=mkb_codes)
    dedup: dict[str, Any] = {}
    for query in retrieval_queries:
        packed = retrieval.retrieve_context(doc_id=doc_id, query=query)
        for chunk in packed:
            existing = dedup.get(chunk.chunk_id)
            if existing is None or chunk.score > existing.score:
                dedup[chunk.chunk_id] = chunk
    top_chunks = sorted(dedup.values(), key=lambda c: c.score, reverse=True)[:CONTEXT_TARGET]
    context_chunks = [_to_chunk_dict(c) for c in top_chunks]

    prompt = (
        f"{SCORES_SYSTEM_PROMPT}\n\n"
        f"doc_id: {doc_id}\n"
        f"Диагностические коды МКБ визита: {', '.join(mkb_codes) if mkb_codes else 'не указаны'}\n"
        f"Поисковые запросы по визиту:\n{json.dumps(retrieval_queries, ensure_ascii=False, indent=2)}\n\n"
        f"Входной JSON визита:\n{json.dumps(appointment, ensure_ascii=False, indent=2)}\n\n"
        "Верни структурированную оценку. "
        "risk_level оцени как юридический риск некорректного заполнения медицинской документации: low/medium/high. "
        "issues: замечания через ';'. "
        "summary: короткая сводка 1-3 строки.\n\n"
        f"Контекст:\n{json.dumps(context_chunks, ensure_ascii=False, indent=2)}"
    )

    structured_llm = llm.with_structured_output(ApiJudgeOutput, include_raw=True)
    resp = structured_llm.invoke(prompt)
    raw = resp.get("raw") if isinstance(resp, dict) else None
    parsed = resp.get("parsed") if isinstance(resp, dict) else None
    parse_error = resp.get("parsing_error") if isinstance(resp, dict) else None

    raw_text = getattr(raw, "content", str(raw)) if raw is not None else ""
    if raw_text:
        log.info("Scoring LLM raw answer (truncated): %s", truncate_text(str(raw_text), 500))
    if parse_error:
        log.error("Scoring structured output parsing error: %s", parse_error)

    if parsed is None:
        return {
            "overall_score": 1,
            "risk_level": "high",
            "score_visit_identification": 1,
            "score_anamnesis": 1,
            "score_inspection": 1,
            "score_dynamic": 1,
            "score_diagnosis": 1,
            "score_recommendations": 1,
            "score_structure": 1,
            "issues": "Ошибка структурированного ответа LLM",
            "summary": "Не удалось получить валидный структурированный ответ от LLM",
        }
    return parsed.model_dump()


def generate_human_readable(llm: ChatOllama, appointment: dict[str, Any], scores: dict[str, Any]) -> str:
    prompt = (
        "Сделай человекочитаемое резюме внутренней оценки качества медицинского приёма. "
        "Язык: русский. Формат: 5-10 предложений без markdown. "
        "Опиши сильные стороны, ключевые замечания, юридические риски некорректного заполнения и приоритетные шаги исправления.\n\n"
        f"Оценки:\n{json.dumps(scores, ensure_ascii=False, indent=2)}\n\n"
        f"Данные визита:\n{json.dumps(appointment, ensure_ascii=False, indent=2)}"
    )
    response = llm.invoke(prompt)
    content = getattr(response, "content", "")
    if isinstance(content, list):
        return " ".join(str(part) for part in content).strip()
    return str(content).strip()


def parse_visit_date(raw_date: Any) -> str | None:
    if raw_date is None:
        return None
    value = str(raw_date).strip()
    if not value:
        return None
    for fmt in ("%d.%m.%Y", "%d.%m.%y", "%Y-%m-%d"):
        try:
            return datetime.strptime(value, fmt).date().isoformat()
        except ValueError:
            continue
    return None


def _append_issue(current: str | None, addition: str) -> str:
    if not current:
        return addition
    return f"{current}; {addition}"


def extract_medkard_row(
    llm: ChatOllama,
    retrieval: RetrievalService,
    appointment: dict[str, Any],
    exact_mkb_index: dict[str, str],
    group_mkb_index: dict[str, str],
    log: logging.Logger,
):
    resolved_doc_id, mkb_codes, matched_mkb = resolve_doc_id_from_manifest(
        appointment=appointment,
        exact_index=exact_mkb_index,
        group_index=group_mkb_index,
    )
    if matched_mkb:
        log.info("Resolved doc_id=%s by MKB=%s", resolved_doc_id, matched_mkb)
    else:
        log.warning("No MKB match in manifest; using fallback doc_id=%s", resolved_doc_id)

    scores = evaluate_scores_with_llm(
        llm=llm,
        retrieval=retrieval,
        doc_id=resolved_doc_id,
        appointment=appointment,
        mkb_codes=mkb_codes,
        log=log,
    )
    if mkb_codes and not matched_mkb:
        scores["issues"] = _append_issue(
            scores.get("issues"),
            "Код МКБ не найден в manifest.csv, использован резервный документ рекомендаций",
        )
    human_readable = generate_human_readable(llm=llm, appointment=appointment, scores=scores)

    visit = appointment.get("Прием") if isinstance(appointment.get("Прием"), dict) else {}
    patient_obj = appointment.get("Пациент")
    inspection_data = appointment.get("ДанныеОсмотра")
    diagnosis_data = appointment.get("Диагнозы")
    services_data = appointment.get("Услуги")

    visit_guid = str(visit.get("GUID", "")).strip()
    if not visit_guid:
        raise ValueError("Missing Прием.GUID for appointment")

    patient = None
    if patient_obj is not None:
        patient = json.dumps(patient_obj, ensure_ascii=False)

    visit_date = parse_visit_date(visit.get("DATE"))

    return (
        visit_guid,
        int(scores["score_visit_identification"]),
        int(scores["score_anamnesis"]),
        int(scores["score_inspection"]),
        int(scores["score_dynamic"]),
        int(scores["score_diagnosis"]),
        int(scores["score_recommendations"]),
        int(scores["score_structure"]),
        str(scores.get("issues", "")).strip() or None,
        str(scores.get("summary", "")).strip() or None,
        int(scores["overall_score"]),
        str(scores["risk_level"]),
        json.dumps(inspection_data, ensure_ascii=False) if inspection_data is not None else None,
        json.dumps(diagnosis_data, ensure_ascii=False) if diagnosis_data is not None else None,
        json.dumps(services_data, ensure_ascii=False) if services_data is not None else None,
        visit_date,
        human_readable or None,
        patient,
    )


def upsert_medkard_rows(conn, rows: list[tuple]) -> None:
    if not rows:
        return
    sql = """
    INSERT INTO public."MedKard" (
      visit_guid_1c,
      score_visit_identification,
      score_anamnes,
      score_inspection,
      score_dynamic,
      score_diagnosis,
      score_recommendations,
      score_structure,
      issues,
      summary,
      score_overall,
      risk_level,
      "Inspection_data",
      diagnosis_data,
      services_data,
      visit_date,
      human_readable,
      patient
    )
    VALUES (
      %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
      %s::jsonb, %s::jsonb, %s::jsonb, %s, %s, %s
    )
    ON CONFLICT (visit_guid_1c) DO UPDATE SET
      score_visit_identification = EXCLUDED.score_visit_identification,
      score_anamnes = EXCLUDED.score_anamnes,
      score_inspection = EXCLUDED.score_inspection,
      score_dynamic = EXCLUDED.score_dynamic,
      score_diagnosis = EXCLUDED.score_diagnosis,
      score_recommendations = EXCLUDED.score_recommendations,
      score_structure = EXCLUDED.score_structure,
      issues = EXCLUDED.issues,
      summary = EXCLUDED.summary,
      score_overall = EXCLUDED.score_overall,
      risk_level = EXCLUDED.risk_level,
      "Inspection_data" = EXCLUDED."Inspection_data",
      diagnosis_data = EXCLUDED.diagnosis_data,
      services_data = EXCLUDED.services_data,
      visit_date = EXCLUDED.visit_date,
      human_readable = EXCLUDED.human_readable,
      patient = EXCLUDED.patient
    """
    with conn.cursor() as cur:
        cur.executemany(sql, rows)


def main() -> None:
    setup_logging(LOG_FILE)
    log = logging.getLogger(__name__)
    settings = Settings()

    store = WeaviateGraphStore(settings)
    try:
        retrieval = RetrievalService(store, settings)
        llm = ChatOllama(model=settings.ollama_chat_model, base_url=settings.ollama_chat_base_url, temperature=0.0)
        appointments = fetch_appointments_from_1c()
        exact_mkb_index, group_mkb_index = load_manifest_mkb_index(MANIFEST_PATH)

        rows = []
        for appointment in appointments:
            rows.append(
                extract_medkard_row(
                    llm=llm,
                    retrieval=retrieval,
                    appointment=appointment,
                    exact_mkb_index=exact_mkb_index,
                    group_mkb_index=group_mkb_index,
                    log=log,
                )
            )

        with connect_postgres() as conn:
            ensure_medkard_table(conn)
            upsert_medkard_rows(conn, rows)
            conn.commit()

        print(json.dumps({"processed": len(rows)}, ensure_ascii=False, indent=2))
    except Exception:
        log.exception("MedKard evaluation pipeline failed")
        raise
    finally:
        store.close()


if __name__ == "__main__":
    main()
