from __future__ import annotations

import os
import re
import urllib.parse

try:
    import psycopg  # type: ignore
except ImportError:  # pragma: no cover
    psycopg = None

try:
    import psycopg2  # type: ignore
except ImportError:  # pragma: no cover
    psycopg2 = None

POSTGRES_DSN = os.getenv("POSTGRES_DSN", "")
POSTGRES_DB = os.getenv("POSTGRES_DB", "")


def extract_db_name_from_dsn(dsn: str) -> str | None:
    parsed = urllib.parse.urlparse(dsn)
    if parsed.scheme and parsed.path and parsed.path != "/":
        return parsed.path.lstrip("/")
    match = re.search(r"(?:^|\\s)(?:dbname|database)\\s*=\\s*([^\\s]+)", dsn)
    if match:
        return match.group(1).strip().strip("'\"")
    return None


def connect_postgres():
    if not POSTGRES_DSN:
        raise ValueError("POSTGRES_DSN is not set")
    if not POSTGRES_DB:
        raise ValueError("POSTGRES_DB is not set")
    db_from_dsn = extract_db_name_from_dsn(POSTGRES_DSN)
    if db_from_dsn and db_from_dsn != POSTGRES_DB:
        raise ValueError(f"POSTGRES_DB ({POSTGRES_DB}) does not match DB in POSTGRES_DSN ({db_from_dsn})")
    if psycopg is not None:
        return psycopg.connect(POSTGRES_DSN)
    if psycopg2 is not None:
        return psycopg2.connect(POSTGRES_DSN)
    raise RuntimeError("Neither psycopg nor psycopg2 is installed")


def ensure_medkard_table(conn) -> None:
    create_sql = """
    CREATE TABLE IF NOT EXISTS public."MedKard" (
      id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      created_at timestamp with time zone NOT NULL DEFAULT now(),
      visit_guid_1c text NOT NULL,
      score_visit_identification integer NOT NULL,
      score_anamnes integer NOT NULL,
      score_inspection integer NOT NULL,
      score_dynamic integer NOT NULL,
      score_diagnosis integer NOT NULL,
      score_recommendations integer NOT NULL,
      score_structure integer NOT NULL,
      issues text NULL,
      summary text NULL,
      score_overall integer NOT NULL,
      risk_level text NOT NULL,
      "Inspection_data" jsonb NULL,
      diagnosis_data jsonb NULL,
      services_data jsonb NULL,
      visit_date date NULL,
      human_readable text NULL,
      patient text NULL,
      CONSTRAINT "MedKard_pkey" PRIMARY KEY (id),
      CONSTRAINT "MedKard_visit_guid_1c_key" UNIQUE (visit_guid_1c)
    ) TABLESPACE pg_default;
    """
    with conn.cursor() as cur:
        cur.execute(create_sql)


def upsert_medkard_rows(conn, rows: list[tuple]) -> None:
    if not rows:
        return
    sql = """
    INSERT INTO public."MedKard" (
      visit_guid_1c,
      score_visit_identification,
      score_anamnes,
      score_inspection,
      score_dynamic,
      score_diagnosis,
      score_recommendations,
      score_structure,
      issues,
      summary,
      score_overall,
      risk_level,
      "Inspection_data",
      diagnosis_data,
      services_data,
      visit_date,
      human_readable,
      patient
    )
    VALUES (
      %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
      %s::jsonb, %s::jsonb, %s::jsonb, %s, %s, %s
    )
    ON CONFLICT (visit_guid_1c) DO UPDATE SET
      score_visit_identification = EXCLUDED.score_visit_identification,
      score_anamnes = EXCLUDED.score_anamnes,
      score_inspection = EXCLUDED.score_inspection,
      score_dynamic = EXCLUDED.score_dynamic,
      score_diagnosis = EXCLUDED.score_diagnosis,
      score_recommendations = EXCLUDED.score_recommendations,
      score_structure = EXCLUDED.score_structure,
      issues = EXCLUDED.issues,
      summary = EXCLUDED.summary,
      score_overall = EXCLUDED.score_overall,
      risk_level = EXCLUDED.risk_level,
      "Inspection_data" = EXCLUDED."Inspection_data",
      diagnosis_data = EXCLUDED.diagnosis_data,
      services_data = EXCLUDED.services_data,
      visit_date = EXCLUDED.visit_date,
      human_readable = EXCLUDED.human_readable,
      patient = EXCLUDED.patient
    """
    with conn.cursor() as cur:
        cur.executemany(sql, rows)
