from __future__ import annotations

import logging
import os
from urllib.parse import quote_plus

from engine.models import MedKardRow

try:
    import psycopg  # type: ignore
except ImportError:  # pragma: no cover
    psycopg = None

try:
    import psycopg2  # type: ignore
except ImportError:  # pragma: no cover
    psycopg2 = None

POSTGRES_HOST = os.getenv("POSTGRES_HOST", "")
POSTGRES_PORT = os.getenv("POSTGRES_PORT", "5432")
POSTGRES_USER = os.getenv("POSTGRES_USER", "")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD", "")
POSTGRES_DB = os.getenv("POSTGRES_DB", "")
POSTGRES_SSLMODE = os.getenv("POSTGRES_SSLMODE", "prefer")
log = logging.getLogger(__name__)


def build_postgres_dsn() -> str:
    if not POSTGRES_HOST:
        raise ValueError("POSTGRES_HOST is not set")
    if not POSTGRES_PORT:
        raise ValueError("POSTGRES_PORT is not set")
    if not POSTGRES_USER:
        raise ValueError("POSTGRES_USER is not set")
    if not POSTGRES_PASSWORD:
        raise ValueError("POSTGRES_PASSWORD is not set")
    if not POSTGRES_DB:
        raise ValueError("POSTGRES_DB is not set")

    user = quote_plus(POSTGRES_USER)
    password = quote_plus(POSTGRES_PASSWORD)
    host = POSTGRES_HOST.strip()
    port = str(POSTGRES_PORT).strip()
    db = POSTGRES_DB.strip()
    sslmode = POSTGRES_SSLMODE.strip() or "prefer"
    return f"postgresql://{user}:{password}@{host}:{port}/{db}?sslmode={sslmode}"


def connect_postgres():
    dsn = build_postgres_dsn()
    host = POSTGRES_HOST.strip()
    port = str(POSTGRES_PORT).strip()
    db = POSTGRES_DB.strip()
    sslmode = POSTGRES_SSLMODE.strip() or "prefer"
    try:
        if psycopg is not None:
            log.info("Connecting to Postgres via psycopg host=%s port=%s db=%s sslmode=%s", host, port, db, sslmode)
            return psycopg.connect(dsn)
        if psycopg2 is not None:
            log.info("Connecting to Postgres via psycopg2 host=%s port=%s db=%s sslmode=%s", host, port, db, sslmode)
            return psycopg2.connect(dsn)
        raise RuntimeError("Neither psycopg nor psycopg2 is installed")
    except Exception:
        log.exception("Postgres connection failed host=%s port=%s db=%s sslmode=%s", host, port, db, sslmode)
        raise


def ensure_medkard_table(conn) -> None:
    create_sql = """
    CREATE TABLE IF NOT EXISTS public."MedKard" (
      id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      created_at timestamp with time zone NOT NULL DEFAULT now(),
      visit_guid_1c text NOT NULL,
      score_visit_identification integer NOT NULL,
      score_anamnes integer NOT NULL,
      score_inspection integer NOT NULL,
      score_dynamic integer NOT NULL,
      score_diagnosis integer NOT NULL,
      score_recommendations integer NOT NULL,
      score_structure integer NOT NULL,
      issues text NULL,
      summary text NULL,
      score_overall integer NOT NULL,
      risk_level text NOT NULL,
      "Inspection_data" jsonb NULL,
      diagnosis_data jsonb NULL,
      services_data jsonb NULL,
      visit_date date NULL,
      human_readable text NULL,
      patient text NULL,
      CONSTRAINT "MedKard_pkey" PRIMARY KEY (id),
      CONSTRAINT "MedKard_visit_guid_1c_key" UNIQUE (visit_guid_1c)
    ) TABLESPACE pg_default;
    """
    try:
        with conn.cursor() as cur:
            cur.execute(create_sql)
        log.info('Ensured Postgres table exists: public."MedKard"')
    except Exception:
        log.exception('Failed to ensure Postgres table public."MedKard"')
        raise


def _to_db_tuple(row: MedKardRow | tuple) -> tuple:
    if isinstance(row, MedKardRow):
        return row.to_db_tuple()
    return row


def _get_visit_guid(row: MedKardRow | tuple) -> str:
    if isinstance(row, MedKardRow):
        return row.visit_guid_1c
    return str(row[0]).strip() if len(row) > 0 else ""


def upsert_medkard_rows(conn, rows: list[MedKardRow | tuple]) -> None:
    if not rows:
        log.debug("Skipping MedKard upsert: empty rows batch")
        return
    sql = """
    INSERT INTO public."MedKard" (
      visit_guid_1c,
      score_visit_identification,
      score_anamnes,
      score_inspection,
      score_dynamic,
      score_diagnosis,
      score_recommendations,
      score_structure,
      issues,
      summary,
      score_overall,
      risk_level,
      "Inspection_data",
      diagnosis_data,
      services_data,
      visit_date,
      human_readable,
      patient
    )
    VALUES (
      %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
      %s::jsonb, %s::jsonb, %s::jsonb, %s, %s, %s
    )
    ON CONFLICT (visit_guid_1c) DO UPDATE SET
      score_visit_identification = EXCLUDED.score_visit_identification,
      score_anamnes = EXCLUDED.score_anamnes,
      score_inspection = EXCLUDED.score_inspection,
      score_dynamic = EXCLUDED.score_dynamic,
      score_diagnosis = EXCLUDED.score_diagnosis,
      score_recommendations = EXCLUDED.score_recommendations,
      score_structure = EXCLUDED.score_structure,
      issues = EXCLUDED.issues,
      summary = EXCLUDED.summary,
      score_overall = EXCLUDED.score_overall,
      risk_level = EXCLUDED.risk_level,
      "Inspection_data" = EXCLUDED."Inspection_data",
      diagnosis_data = EXCLUDED.diagnosis_data,
      services_data = EXCLUDED.services_data,
      visit_date = EXCLUDED.visit_date,
      human_readable = EXCLUDED.human_readable,
      patient = EXCLUDED.patient
    """
    try:
        with conn.cursor() as cur:
            for idx, row in enumerate(rows):
                visit_guid = _get_visit_guid(row)
                row_tuple = _to_db_tuple(row)
                log.info("MedKard upsert try index=%d visit_guid=%s", idx, visit_guid or "<missing>")
                try:
                    cur.execute(sql, row_tuple)
                    log.info("MedKard upsert success index=%d visit_guid=%s", idx, visit_guid or "<missing>")
                except Exception:
                    log.exception("MedKard upsert failed index=%d visit_guid=%s", idx, visit_guid or "<missing>")
                    raise
        log.info("Upserted MedKard rows batch count=%d", len(rows))
    except Exception:
        log.exception("Failed MedKard upsert batch count=%d", len(rows))
        raise


def is_visit_processed(conn, visit_guid_1c: str) -> bool:
    try:
        with conn.cursor() as cur:
            cur.execute(
                'SELECT 1 FROM public."MedKard" WHERE visit_guid_1c = %s LIMIT 1',
                (visit_guid_1c,),
            )
            processed = cur.fetchone() is not None
        log.debug("Checked MedKard existing visit_guid=%s processed=%s", visit_guid_1c, processed)
        return processed
    except Exception:
        log.exception("Failed MedKard processed check visit_guid=%s", visit_guid_1c)
        raise


def upsert_medkard_row(conn, row: MedKardRow | tuple) -> None:
    upsert_medkard_rows(conn, [row])
